### PR TITLE
Fix #285 Support rich menu switch action

### LINKED ISSUE #285: Support rich menu switch action
- Rich menu switch action has been added to action object
- postback.params object for rich menu switch action has been added to Postback event

https://developers.line.biz/en/news/2021/06/21/switch-between-multiple-rich-menus/

this is related to #284 .

### PR DESCRIPTION
**Pull request by gotokatsuya**
#285

### CODE REVIEW

**Comment by kkdai** [comment]
@clsung Would you help to check this one?

**Comment by clsung** [comment]
Can you add some unit tests?

**Comment by gotokatsuya** [comment]
OK

**Comment by gotokatsuya** [comment]
@clsung I just add webhook test. Could you check it? Let me know if you have better test.

**Review by clsung — APPROVED** [review]
LGTM

**Review by kkdai — APPROVED** [review]
LGTM

**Pull request merged**
