### PR TITLE
bugfix: message.Type() is a empty value

### PR DESCRIPTION
**Pull request by 1046102779**
issue: https://github.com/line/line-bot-sdk-go/issues/332

cc @kkdai @clsung 

Signed-off-by: 1046102779 <seachen@tencent.com>

### CODE REVIEW

**Comment by 1046102779** [comment]
cc @kkdai.

Help me review this PR.  Thanks.

**Comment by 1046102779** [comment]
cc @kkdai

**Comment by kkdai** [comment]
Hi @1046102779 
Please help to check my comment in this PR, thank you.

**Comment by yujinlin0224** [comment]
Any update?

My temporary solution:
```go
_, ok := event.Message.(*linebot.TextMessage)
```

**Comment by Yang-33** [comment]
@yujinlin0224 
This is old package(`linebot`) now. Although line-bot-sdk-go is welcome to any patch, I highly recommend you use `linebot.webhook` package and discard old code from your application.

`linebot.webhook` doesn't have this issue. https://github.com/line/line-bot-sdk-go/blob/62e2928fdcaa9c843fc3585434d5dc2d87867bb7/examples/kitchensink/server.go#L116-L129 is an example of new package and you can understand how to use it.

**Review by kkdai — APPROVED** [review]
LGTM

**Pull request closed without merging**
