### PR TITLE
add flex property on filler component

### PR DESCRIPTION
**Pull request by johanavril**
[API reference](https://developers.line.biz/en/reference/messaging-api/#filler)

### CODE REVIEW

**Comment by johanavril** [comment]
hi, I add test but the diff hit on codecov still 0%. Could anyone help me? Thank you.

**Comment by oklahomer** [comment]
@johanavril That probably is due to the absence of [JSON marshaling test](https://codecov.io/gh/line/line-bot-sdk-go/pull/183/diff?src=pr&el=tree#). Unmarshaling is tested in the new lines while `MarshalJSON` is not so the test actually passes even when https://github.com/line/line-bot-sdk-go/pull/183/files#diff-8e69f58e71fe924131e7883eb77898b7R418 is removed.

**Comment by johanavril** [comment]
@oklahomer Ok thank you, then is it fine if I add a json marshaling test ? Because there aren't any json marshalling tests before.

**Comment by oklahomer** [comment]
@johanavril Thank you for the offer. Yes, I think that would be better.

**Comment by johanavril** [comment]
now all checks have passed, thanks for the help @oklahomer could you review the PR ? thank you

**Comment by oklahomer** [comment]
Thank you for the changes. LGTM 👍

**Pull request merged**
